services:
  postgres:
    image: postgres:latest
    container_name: my-pg
    environment:
      POSTGRES_PASSWORD: "111111"
      POSTGRES_DB: "gateway"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: my-redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "111111"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: my-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped

volumes:
  pg-data:
  redis-data:
  qdrant-data:
