apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-gateway.fullname" . }}-frontend
  labels:
    {{- include "ai-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ai-gateway.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
